name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, fiber]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm install and build
        run: |
          npm ci
          npm run refresh-kbs
          npm run build
